name: Cypress Tests
on:
    push:
        branches:
            - main # Replace with your branch name if needed
    pull_request:
        branches:
            - main # Replace with your branch name if needed

jobs:
    cypress:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16' # Replace with your desired Node.js version

            - name: Install dependencies
              run: npm ci

            - name: Open Application via Vite
              run: pm run dev &

            - name: Wait for server to start
              run: sleep 10

            - name: Run Cypress
              run: npm run cypress:open
